# Generated by Django 4.1.6 on 2023-02-14 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='heart_rate',
            field=models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxLengthValidator(120)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxLengthValidator(120)]),
        ),
    ]
